services:
  db:
    image: mysql:latest
    container_name: ${DOCKER_DB_CONTAINER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes: 
      - ./db/volume:/var/lib/mysql
      - ./db/dump-nodata.sql:/docker-entrypoint-initdb.d/dump.sql
